// AUTO-GENERATED by `env-manager ts` - do not edit
import { z } from 'zod';

const env = z
	.object({
		GOOGLE_MAPS_API_KEY: z.string(),
		GOOGLE_SEARCH_API_KEY: z.string().optional(),
		GOOGLE_SEARCH_ENGINE_ID: z.string().optional(),
		OPENROUTER_API_KEY: z.string().regex(/^sk-or-v1-/),
	})
	.parse(process.env);

export default env;
